import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Privacy() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Privacy TikTok</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Privacy</h1>
      </main>
    </div>
  )
}
